#!/usr/bin/env python3
# -*- coding:utf8 -*-

import sys

import preprocess as st
from wh_ask import WhQuestionGenerator
from binary_ask import BinaryQuestionGenerator
from question_runner import QuestionRunner

def main(text, n_questions):

    # Instantiate our preprocessor and get the processed doc
    preprocessor = st.Preprocessor(text)
    processed_doc = preprocessor.doc

    # get the avg coref len of the doc (to pass to rankers)
    avg_coref_len = preprocessor.avg_coref_len

    # Instantiate our question generators
    wh_gen = WhQuestionGenerator()
    binary_gen = BinaryQuestionGenerator()

    # Instantiate our question runner
    question_generator = QuestionRunner(processed_doc,
                                        avg_coref_len,
                                        wh_gen,
                                        binary_gen)

    # Final print output
    question_generator.generate_questions(n_questions)

if __name__ == "__main__":

    # Ensure 2 arguments
    if len(sys.argv) != 3:
        print("Usage: ./ask ARTICLE_TXT NUM_QUESTIONS")
        sys.exit(1)

    # Read string from 1 text file. 
    # TODO: extend this to a directory of files
    INPUT_TXT = sys.argv[1]

    # validate that n_questions is an integer
    if not sys.argv[2].isdigit():
        print("NUM_QUESTIONS must be an integer")
        sys.exit(1)

    N_QUESTIONS = int(sys.argv[2])

    with open(INPUT_TXT, 'r') as file:
        TEXT = file.read()

    main(TEXT, N_QUESTIONS)
